language: ruby

branches:
  only:
    - main

rvm:
  # MRI
  - ruby-head
  - 3.0
  - 2.7
  - 2.6
  - jruby
  - truffleruby

jobs:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: truffleruby

  fast_finish: true
